apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  labels:
    app.kubernetes.io/name: buildkitd
    app.kubernetes.io/instance: buildkitd
    app.kubernetes.io/version: v0.9.2-rootless
    app.kubernetes.io/component: builder
    app.kubernetes.io/part-of: f2
    app.kubernetes.io/managed-by: helm
spec:
  clusterIP: None
  ports:
    - name: daemon
      port: 1234
      targetPort: daemon
  selector:
    app.kubernetes.io/name: buildkitd
    app.kubernetes.io/instance: buildkitd

---
apiVersion: v1
kind: Service
metadata:
  name: buildkitd-0
spec:
  ports:
    - name: daemon
      port: 1234
      nodePort: 30000
      targetPort: daemon
  selector:
    statefulset.kubernetes.io/pod-name: buildkitd-0
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: buildkitd-1
spec:
  ports:
    - name: daemon
      port: 1234
      nodePort: 31000
      targetPort: daemon
  selector:
    statefulset.kubernetes.io/pod-name: buildkitd-1
  type: NodePort
