apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: buildkitd
  labels:
    app.kubernetes.io/name: buildkitd
    app.kubernetes.io/instance: buildkitd
    app.kubernetes.io/version: v0.9.2-rootless
    app.kubernetes.io/component: builder
    app.kubernetes.io/part-of: f2
    app.kubernetes.io/managed-by: helm
spec:
  serviceName: buildkitd
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: buildkitd
      app.kubernetes.io/instance: buildkitd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: buildkitd
        app.kubernetes.io/instance: buildkitd
      annotations:
        container.apparmor.security.beta.kubernetes.io/buildkitd: unconfined
        container.seccomp.security.alpha.kubernetes.io/buildkitd: unconfined
    spec:
      serviceAccountName: buildkitd
      containers:
        - name: buildkitd
          image: moby/buildkit:v0.9.2-rootless
          args:
            - --oci-worker-no-process-sandbox
            - --addr=unix:///run/user/1000/buildkit/buildkitd.sock
            - --addr=tcp://0.0.0.0:1234
          ports:
            - name: daemon
              protocol: TCP
              containerPort: 1234
          volumeMounts:
            - name: cache
              mountPath: /home/user/.local/share/buildkit
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            # NOTE: To change UID/GID, you need to rebuild the image
            runAsUser: 1000
            runAsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: cache
        labels:
          app.kubernetes.io/name: buildkitd
          app.kubernetes.io/instance: buildkitd
          app.kubernetes.io/version: v0.9.2-rootless
          app.kubernetes.io/component: builder
          app.kubernetes.io/part-of: f2
          app.kubernetes.io/managed-by: helm
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
