apiVersion: hephaestus.dominodatalab.com/v1
kind: ImageCache
metadata:
  name: base-images
spec:
  images:
    - debian:11.2
    - centos:centos8.4.2105
    - python:3.10.1
#  registryAuth:
#    - server: https://index.docker.io/v1/
#      basicAuth:
#        username: foo
#        password: bar
#      secret:
#        name: registry-credentials
#        namespace: default
#      cloudProvided: true
