name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache Go tools
        uses: actions/cache@v2
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tools-${{ hashFiles('tools/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-tools-

      - name: Install tools
        run: make tools

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Unit test
        run: make test

  sdks:
    runs-on: ubuntu-latest
#    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install KinD
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          skipClusterCreation: true

      - name: Generate SDKS
        run: make sdks

      - name: Generate Java JAR
        run: docker run --rm -v $HOME/.m2:/root/.m2 -v $(pwd)/sdks/java:/wd --workdir /wd maven:3-openjdk-8 mvn -s settings.xml package

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: sdks/java/target/*.jar
          if-no-files-found: error
