name: Image Security Updates

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:
    inputs:
      buildkitVersion:
        type: string
        description: Override Buildkit image version defined in Helm chart (e.g. v0.10.3)

jobs:
  check-input:
    name: Check user input
    runs-on: ubuntu-latest
    if: github.event.inputs.buildkitVersion != ''
    steps:
      - name: Validate buildkit version
        run: curl --head --fail-with-body https://hub.docker.com/v2/repositories/moby/buildkit/tags/${{ inputs.buildkitVersion }}

  buildkit:
    name: Buildkit
    runs-on: ubuntu-latest
    needs: [check-input]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: image_tag
        name: Extract image details from Helm values
        uses: mikefarah/yq@v4.28.2
        with:
          cmd: test -n "${{ inputs.buildkitVersion }}" && echo "${{ inputs.buildkitVersion }}" || yq '.buildkit.image.tag' deployments/helm/hephaestus/values.yaml | sed 's/-rootless//'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push rootless Buildkit image to Quay
        uses: docker/build-push-action@v3
        with:
          push: true
          target: root
          context: build/buildkit
          build-args: BUILDKIT_TAG=${{ steps.image_tag.outputs.result }}
          tags: quay.io/domino/buildkit:${{ steps.image_tag.outputs.result }}


  buildkit-rootless:
    name: Buildkit Rootless
    runs-on: ubuntu-latest
    needs: [check-input]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: image_tag
        name: Extract image details from Helm values
        uses: mikefarah/yq@v4.28.2
        with:
          cmd: test -n "${{ inputs.buildkitVersion }}" && echo "${{ inputs.buildkitVersion }}-rootless" || yq '.buildkit.image.tag' deployments/helm/hephaestus/values.yaml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push rootless Buildkit image to Quay
        uses: docker/build-push-action@v3
        with:
          push: true
          target: rootless
          context: build/buildkit
          build-args: BUILDKIT_TAG=${{ steps.image_tag.outputs.result }}
          tags: quay.io/domino/buildkit:${{ steps.image_tag.outputs.result }}
